### ISSUE TITLE
SockIOPool.shutDown() seems has a dead lock with selfMaint()

### ISSUE THREAD

**Issue by bitsf** [gwhalin/Memcached-Java-Client#1]
When I run the class MemCachedBench.java, I find sometimes the programme can't exit normally.
Then I debug it with eclipse, I found the "maintThread" is still waiting at line 1298, seems like dead lock.

```
protected void selfMaint() {
    if ( log.isDebugEnabled() )
        log.debug( "++++ Starting self maintenance...." );

    // go through avail sockets and create sockets
    // as needed to maintain pool settings
    Map needSockets =
        new HashMap();
```

*************\*  synchronized( this ) {
            // find out how many to create
            for ( Iterator i = availPool.keySet().iterator(); i.hasNext(); ) {

I think maybe you shouldn't use "synchronized" in Method shutDown(), or you should use "this.wait(500);" to replace "Thread.sleep( 500 );".

**Comment by newroot** [comment]
Try the newer version. 2.5.1
