### ISSUE TITLE
client unable to set objects greater than 1 Mb in version 2.5.1, was able to in 2.0.1

### ISSUE THREAD

**Issue by ghost** [gwhalin/Memcached-Java-Client#11]
I just noticed the latest update of the memcached-java-client after playing around with spymemcached and then reading about the performance increases. Great work!

I do have one issue...

With 2.0.1, I was able to set objects > 1 Mb by increasing the slab max (passing in the -I flag to memcached). With 2.5.1, the set command returns false if the object size is > 1 Mb. I checked the source code and didn't see a limit being set.

Any ideas? Thanks for you time.
Owen

I'm running memcached version 1.4.3 with the following settings

PORT="11211"
USER="nobody"
MAXCONN="1024"
OPTIONS="-I 8m"
CACHESIZE=1536

To test, I created a Junit test and assertTrue on the set command for byte arrays of size 1000000 and 2000000.

**Comment by xuhuleon** [comment]
hi owentran,
Thank you for your time to try our memcached client. I have solved your question.
Suppose you have code like this "SockIOPool pool = SockIOPool.getInstance();", you should add "pool.setBufferSize(3 \* 1024 \* 1025);" if you want use value bigger than 1 m. (default buffer size of memcached client is 1m)

Please let us know if you still have trouble with this client.

**Comment by ghost** [comment]
That's exactly what I was looking for. I set the value and it works like a charm. Thanks.
