### ISSUE TITLE
BufferOverflowException when getMulti with lots of keys

### ISSUE THREAD

**Issue by velna** [gwhalin/Memcached-Java-Client#14]
java.nio.BufferOverflowException
    at java.nio.Buffer.nextPutIndex(Buffer.java:501)
    at java.nio.DirectByteBuffer.putLong(DirectByteBuffer.java:738)
    at com.schooner.MemCached.BinaryClient$NIOLoader$Connection.<init>(Unknown Source)
    at com.schooner.MemCached.BinaryClient$NIOLoader.doMulti(Unknown Source)
    at com.schooner.MemCached.BinaryClient$NIOLoader.doMulti(Unknown Source)
    at com.schooner.MemCached.BinaryClient.getMulti(Unknown Source)
    at com.danga.MemCached.MemCachedClient.getMulti(Unknown Source)
    at com.danga.MemCached.MemCachedClient.getMulti(Unknown Source)

should calculate the size of keys, instead of hard code 10K bytes

**Comment by velna** [comment]
here is the patch:
com.schooner.MemCached.BinaryClient.NIOLoader.Connection.Connection(SchoonerSockIO, ArrayList<String>){
                this.sock = sock;
                List<byte[]> bufList = new ArrayList<byte[]>(keys.size());
                int size  = 0;
                for (String key : keys) {
                    byte[] buf = key.getBytes();
                    bufList.add(buf);
                    size += buf.length;
                }
                size = size + (bufList.size()+1)*24;
                outgoing = ByteBuffer.allocateDirect(size);
                outgoing.clear();
                for(byte[] buf: bufList){
                    outgoing.put(MAGIC_REQ);
                    outgoing.put(OPCODE_GETKQ);
                    outgoing.putShort((short) buf.length);
                    outgoing.putInt(0);
                    outgoing.putInt(buf.length);
                    outgoing.putInt(0);
                    outgoing.putLong(0L);
                    outgoing.put(buf);
                }
                outgoing.put(MAGIC_REQ);
                outgoing.put(OPCODE_NOOP);
                outgoing.putShort((short) 0);
                outgoing.putInt(0);
                outgoing.putLong(0L);
                outgoing.putLong(0L);
                outgoing.flip();
                channel = (SocketChannel) sock.getChannel();
                if (channel == null)
                    throw new IOException("dead connection to: " + sock.getHost());

```
            channel.configureBlocking(false);
            channel.register(selector, SelectionKey.OP_WRITE, this);
```

}

**Comment by newroot** [comment]
Thanks, velna

**Comment by newroot** [comment]
The modification accepted.

Thanks again, Velna
