### ISSUE TITLE
getMultiArray() does not return all objects cacehed

### ISSUE THREAD

**Issue by kwang** [gwhalin/Memcached-Java-Client#15]
Hi all,

Has anybody experienced problems using java client's getMultiArray()
method(Schooner memcached client 2.5.0)?

We run into this problem recently - getMultiArray() does not return
all objects specified. But when trying to load the missing objects
using get() method one by one, they are all fine. Those objects also
exist in memcached server with proper expiration time when checking
with 'stats cachedump'.

Any help appreciated, Thanks!

**Comment by newroot** [comment]
Which protocol are you using? ascii or binary?

If you were using binary protocol, probably this issue is the same with the issue 14.
https://github.com/gwhalin/Memcached-Java-Client/issues/closed#issue/14

Try to checkout the source code(performance branch) from the github, and build the jar package by yourself, or download 2.5.2 for a try.

If the issue still exist, please let us know.

Thanks.

Xingen Wang.

**Comment by kwang** [comment]
Thanks for the reply. 

We are using Ascii client. We restarted the server and the problem went away. Based on this, I don't think the problem was caused by the size of the key. 

One thing worth mentioning is that at the same time this problem occurred, we observed that the number of concurrent connections dropped from ~30 to ~15. 

Could it be related with reuse of the connection? Our connection and read timeout are set to 3 seconds.

Thanks again.

**Comment by newroot** [comment]
Can you help repeat the issue? If yes, could you please send us those snippets?

Actually, GetMulti APIs were not strongly tested, and they are processed with different stragetagies.

We plan to re-write the implementation of the multi-get APIs and release a new version.

Xingen Wang

**Comment by pussinboots** [comment]
Hello anybody i had the same problem and i fixed.

I could commit it or send the changed code per mail.

**Comment by newroot** [comment]
Thanks, pussinboots.

Could you please send the source code to me? Here is my email address:
new.root@gmail.com

Thanks.

**Comment by newroot** [comment]
I have accepted pussinboots's modification, thanks for the effort.

Please download  https://github.com/downloads/gwhalin/Memcached-Java-Client/java_memcached-release_2.5.3.jar for the bug fix version.
