### ISSUE TITLE
byte[] is not properly stored when client.setPrimitiveAsString(true)

### ISSUE THREAD

**Issue by PiouseLeo** [gwhalin/Memcached-Java-Client#16]
Once the configuration setPrimitiveAsString is set true, the following code:
byte[] bytes = new byte[];
client.set(bytes);

will actually act as:
client.set(bytes.toString().getBytes[]); //according to line 392, AscIIClient.java
while "bytes.toString()" will return something like "[B@1837697", which is obviously wrong.

Is this a bug, or I'm using MemcacheClient in the wrong way?

**Comment by newroot** [comment]
setPrimitiveAsString means convert all the data object as string, and store them into memcached server. 

In most cases, you should not use this flag, unless you have customized toString() in your own data object.

Thanks anyway for the comments.

**Comment by PiouseLeo** [comment]
Thanks for your reply. It seems that I have misunderstood this option. I'll fix my code soon.
