### ISSUE TITLE
Logger is too weak

### ISSUE THREAD

**Issue by PiouseLeo** [gwhalin/Memcached-Java-Client#17]
gwhalin's memcached client implements a Logger itself. 

But the logger is really weak. Could it  support  some mechanism which enables users to apply an alternative Logger implementation such as log4j?

**Comment by newroot** [comment]
Good suggestion, we try to add logger support in next release.

We write our own logger in previous version, that's because we want to provide a minimum dependencies with other java libraries. 

But considering the popular usage of the logger, we will add a logger support in next release.

**Comment by PiouseLeo** [comment]
Thank you.
