### ISSUE TITLE
failback is not working?

### ISSUE THREAD

**Issue by bill2004158** [gwhalin/Memcached-Java-Client#18]
I am working on the latest release java_memcached-release_2.5.3.jar.

I have added lots of cache in Memche,
and at least 50 get call per request.

recently, my site get very slow,
and get lots of error message:
com.schooner.MemCached.SchoonerSockIOPool Tue May 03 21:18:37 PDT 2011 - ++++ failed to get SockIO obj for: 

it  seems it try to connect the memcached server for every get request when server DOWN.
although I have config :
pool.setFailback(false);

<b>so how can I stop it trying to connect dead server?</b>

another issue:

<pre>
    protected final SchoonerSockIO createSocketWithAdd(String host) {

        SchoonerSockIO socket = null;
        try {
            poolCurrentConn.get(host).addAndGet(1);
            if (isTcp) {
                socket = new TCPSockIO(this, host, bufferSize, this.socketTO, this.socketConnectTO, this.nagle, true);
            } else {
                socket = new UDPSockIO(this, host, bufferSize, socketTO, true);
            }
        } catch (Exception ex) {
            log.error("++++ failed to get SockIO obj for: " + host);
            // log.error(ex.getMessage(), ex);
            socket = null;
            poolCurrentConn.get(host).decrementAndGet();
        }

        return socket;
    }
</pre>

will it clean up the direct memory if connection fail?

I have got some of this exception:

<pre>
Caused by: java.lang.OutOfMemoryError: Direct buffer memory
    at java.nio.Bits.reserveMemory(Bits.java:632)
    at java.nio.DirectByteBuffer.<init>(DirectByteBuffer.java:95)
    at java.nio.ByteBuffer.allocateDirect(ByteBuffer.java:288)
    at com.schooner.MemCached.SchoonerSockIOPool$TCPSockIO.<init>(Unknown Source)
    at com.schooner.MemCached.SchoonerSockIOPool.createSocketWithAdd(Unknown Source)
    at com.schooner.MemCached.SchoonerSockIOPool.getConnection(Unknown Source)
    at com.schooner.MemCached.SchoonerSockIOPool.getSock(Unknown Source)
    at com.schooner.MemCached.AscIIClient.get(Unknown Source)
    at com.schooner.MemCached.AscIIClient.get(Unknown Source)
    at com.schooner.MemCached.AscIIClient.get(Unknown Source)
    at com.danga.MemCached.MemCachedClient.get(Unknown Source)
    at tws.webapp.cache.MemcachedCache.get(Unknown Source)
</pre>

**Comment by bill2004158** [comment]
the log is:

<pre>
log.error("++++ failed to get SockIO obj for: " + host);
</pre>


can you add error msg in the logger.
so we can make sure why connection fail.

**Comment by newroot** [comment]
In 2.5.x, failback and failover and mocked in our real implementation. Since due to our investigation, we found it slow down the performance.

DirectBuffer can increase the performance, while if the memcached server crashed, it will always allocate direct buffer and wait for the gc of VM. It will finally cause OutOfMemoryError.

**Comment by newroot** [comment]
In version 2.6.0, we enabled the log of detailed error information, but we still didn't add failover support.

Since if we do like this, it will never failback. While in current implementation, failback is automatic.

If we get rid of the direct buffer, we can solve the OutOfMemoryError. We will do a deep investigation for this issue.

Thanks anyway for the information.

**Comment by mengli** [comment]
Hi bill2004158,

We add "failback" support in release 2.6.1 which you can download and have a try.

We also re-implement the connection pool based on Apache commons pool in this release and OutOfMemory error disappeared in our test.

Really thank you for your suggestion.

Meng Li
