### ISSUE TITLE
getMulti return null value in map in 2.5.3

### ISSUE THREAD

**Issue by hanguokai** [gwhalin/Memcached-Java-Client#19]
for your java docs, getMulti return a map, if key are not found, the key is not entered into the hashmap. 
It's no problem at 2.5.1, but in 2.5.3 getMulti return null value in a map that key are not found.

eg. client.getMulti(new String[] {"xxx"}) , results are:
{}  in 2.5.1, 
{xxx=null} in 2.5.3

**Comment by newroot** [comment]
Thanks for the information.

We will fix it in next version.

On Mon, May 9, 2011 at 5:36 PM, hanguokai <
reply@reply.github.com>wrote:

> for your java docs, getMulti return a map, if key are not found, the key is
> not entered into the hashmap.
> It's no problem at 2.5.1, but in 2.5.3 getMulti return null value in a map
> that key are not found.
> 
> eg. client.getMulti(new String[] {"xxx"}) , results are:
> {}  in 2.5.1,
> {xxx=null} in 2.5.3
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/gwhalin/Memcached-Java-Client/issues/19

## 

Xingen Wang

**Comment by newroot** [comment]
Fixed in version 2.6.0.

In version 2.6.0, we add slf4j support, you can use any log mechanism as you want。
