### ISSUE TITLE
Why there're lots of warning logs for getMulti?

### ISSUE THREAD

**Issue by dracoyang** [gwhalin/Memcached-Java-Client#26]
Hi, Everyone:  
    I always get warnings when I call getMulti, the message is as follows:  
_WARN com.danga.MemCached.MemCachedClient - Caught the aforementioned exception on Connection to localhost:11211 with 1 bufs; done is true_

   Is it normal or any bug caused this?

**Comment by mengli** [comment]
Hi dracoyang,

We improved the log system of our client using slf4j and it is still not finished, so there may be too much log info in the console. This is not a bug in your program. I have fixed it.

Meng Lee

**Comment by sslai** [comment]
It has been fixed on which release version?

**Comment by mengli** [comment]
Please update to the latest release 2.6.3, It should fix this issue.
