### ISSUE TITLE
New Feature Request.

### ISSUE THREAD

**Issue by bhargavmist** [gwhalin/Memcached-Java-Client#27]
Hi Mengli,

We are currently using the Memcached client and providing the pool parameters through our custom configuration system. We are using the client object as a spring singleton wired into our main codebase.
The issue we are facing is, we want to refresh the pool when any config value is changed in our config system. 

In order to do so there should be a method in SchoonerSockIOPool class which will remove the pool object from "pools" HashMap. This method will take in poolname as argument and will remove that object from the HashMap.

If we can do this then we can remove the pool object if any config value is changed and then reinitialize the pool at runtime with new values. With addition of this feature we don't have to recycle our servers everytime a config value is changed.

I was wondering how difficult it would be for you to add this feature?

Thank you for your time.

Regards,
bhargav

**Comment by mengli** [comment]
Hi,

There is a method called "shutdown" in SchoonerSockIOPool, I think you can shutdown whole pools and then recreate it.

Meng Li

**Comment by bhargavmist** [comment]
Yes but shutdown will not remove the previous object from the hashmap
right. So thus would be a memory leak eventually ! No??

Thanks

On Saturday, August 6, 2011, mengli
reply@reply.github.com
wrote:

**Comment by mengli** [comment]
Actually shutdown will remove all the connection pool which is maintained by SchoonerSockIOPool and all the sockets will be closed safely, so no memory leak will occur.

You can re-create specified connection pool after shutting it down. Don't forget to initialize the new connection pool, :)

Meng Lee

**Comment by bhargavmist** [comment]
Ah ok, let me give it a try.

Thanks mengli.

On Sunday, August 7, 2011, mengli
reply@reply.github.com
wrote:

**Comment by newroot** [comment]
Thanks for the immediate response.

Xingen Wang
