### ISSUE TITLE
Stats Cache Dump Only Works with the ASCII Protocol?

### ISSUE THREAD

**Issue by p-ryan** [gwhalin/Memcached-Java-Client#28]
I'm able to use MemCachedClient.statsCacheDump successfully when connecting to a Memcached server using the ASCII protocol, but no items are returned when connecting using the binary protocol with SASL.  Other operations work over the binary protocol with SASL, including the stats, statsSlabs and statsItems.

I'm using java-memcached-2.6.2.jar from the performance branch with JDK 6u26 32-bit on Linux.  The Memcached server is 1.4.6 with libevent 2.0.12-stable.  It is running with the following options:

memcached -d -p 11211 -u nobody -m 256 -c 1024 -P /var/run/memcached/memcached.pid -S

**Comment by mengli** [comment]
Hi p-ryan

Memcached 1.4.5 don't support stats cachedump in the binary protocol, please refer the following issus: 
https://groups.google.com/group/memcached/browse_thread/thread/cdb563f735fa6553

Meng Lee

**Comment by p-ryan** [comment]
Thanks for the response!
