### ISSUE TITLE
java memcached client 2.5 and 2.6  get() and getmulti() bug?

### ISSUE THREAD

**Issue by weiqinyang** [gwhalin/Memcached-Java-Client#30]
When mysql memcached client set some data to memcached, other language memcached client can get the value,but Java memcached client whth version 2.5 and 2.6 occuer following error and return null (version 2.0.1 runs  well):

com.danga.MemCached.MemCachedClient Tue Aug 16 11:17:56 CST 2011 - ++++ exception thrown while trying to get object from cache for key: test117
com.danga.MemCached.MemCachedClient Tue Aug 16 11:17:56 CST 2011 - invalid stream header: 76616C75
java.io.StreamCorruptedException: invalid stream header: 76616C75
    at java.io.ObjectInputStream.readStreamHeader(Unknown Source)
    at java.io.ObjectInputStream.<init>(Unknown Source)
    at com.schooner.MemCached.ObjectTransCoder.decode(ObjectTransCoder.java:57)
    at com.schooner.MemCached.AscIIClient.get(AscIIClient.java:761)
    at com.schooner.MemCached.AscIIClient.get(AscIIClient.java:612)
    at com.schooner.MemCached.AscIIClient.get(AscIIClient.java:608)
    at com.danga.MemCached.MemCachedClient.get(MemCachedClient.java:1047)
    at TestM.main(TestM.java:56)

 I found this problem caused by  the code :

AscIIClient.java at  line 755:
...
 if(transCoder != null)
            {
                InputStream in = input;
                if((flag & 2) == 2)
                    in = new GZIPInputStream(in);
                if(classLoader == null)
                    o = transCoder.decode(in);
                else
                    o = ((ObjectTransCoder)transCoder).decode(in, classLoader);
            }
}
...

the code can't judge 'primitiveAsString',so the error happened.I modified the code like this, everything is normal:
...
else if (transCoder != null) {
                    // decode object with default transcoder.
                    InputStream in = input;
                    //
                    byte[] buf = ((SockInputStream) in).getBuffer();

```
                if ((flag & F_COMPRESSED) == F_COMPRESSED)
                    in = new GZIPInputStream(in);

                if (primitiveAsString || asString) {
                    o = new String(buf, defaultEncoding);
                } else{
                    if (classLoader == null)
                      o = transCoder.decode(in);
                    else
                      o = ((ObjectTransCoder) transCoder).decode(in, classLoader);
                ...
```

and  getMulti() and doMulti() method is the same reason.

**Comment by weiqinyang** [comment]
Modified the code AscIIClient.java as the up mentioned, it may occuer other error: set Object to memcached,like ArrayList Object,it can't be getted correcttly.

**Comment by mengli** [comment]
Hi weiqinyang,

I try to store and get Java object with array list type, and our client works correctly.
The following is my test case:

package com.schooner.MemCached;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

import com.danga.MemCached.MemCachedClient;
import com.danga.MemCached.SockIOPool;

public class Test {

```
public static final class TestClass implements Serializable {

    private static final long serialVersionUID = -6676639726514578903L;
    private String field1;
    private String field2;
    private Integer field3;

    public TestClass(String field1, String field2, Integer field3) {
        this.field1 = field1;
        this.field2 = field2;
        this.field3 = field3;
    }

    public String getField1() {
        return this.field1;
    }

    public String getField2() {
        return this.field2;
    }

    public Integer getField3() {
        return this.field3;
    }

    public boolean equals(Object o) {
        if (this == o)
            return true;
        if (!(o instanceof TestClass))
            return false;

        TestClass obj = (TestClass) o;

        return ((this.field1 == obj.getField1() || (this.field1 != null && this.field1.equals(obj.getField1())))
                && (this.field2 == obj.getField2() || (this.field2 != null && this.field2.equals(obj.getField2()))) && (this.field3 == obj
                .getField3() || (this.field3 != null && this.field3.equals(obj.getField3()))));
    }
}

public static void main(String[] args) throws Exception {
    String servers = System.getProperty("memcached.host");
    String[] serverlist = servers.split(",");

    // initialize the pool for memcache servers
    SockIOPool pool = SockIOPool.getInstance("test");
    pool.setBufferSize(3 * 1024 * 1024);
    pool.setServers(serverlist);
    pool.initialize();

    MemCachedClient mc = new MemCachedClient("test");
    List<TestClass> list = new ArrayList<TestClass>();

    for (int i = 0; i < 10; i++) {
        list.add(new TestClass("value" + i, "value" + i, i));
    }
    mc.set("TestClass", list);
    List<TestClass> ret = (List<TestClass>)mc.get("TestClass");
    for (int i = 0; i < 10; i++) {
        System.out.println(list.get(i).getField1());
    }
}
```

}

Could you give a try and update your feedback?

Meng Li
