### ISSUE TITLE
BinaryClient should use primitiveAsString mode for all counter operations

### ISSUE THREAD

**Issue by ghost** [gwhalin/Memcached-Java-Client#32]
It's easy to make mistakes with counter operations. The client should use primitive as String at all times with counters:

```
    final MemCachedClient client = new MemCachedClient( true, true );

    // fails without this line below
    client.setPrimitiveAsString( true );

    final String key = "testKey" + Math.random();
    client.storeCounter( key, 3 );
    client.incr( key );

    // prints 4 if asString, -1 if not
    System.out.println( client.getCounter( key ) );
```

**Comment by newroot** [comment]
asString means the value is stored in string format.

incr only support this string mode.

This issue won't fix in later release, please setPrimitiveAsString before using this feature.

Sorry for the inconvenince.
