### ISSUE TITLE
feature request: storeCounter with expiry

### ISSUE THREAD

**Issue by ghost** [gwhalin/Memcached-Java-Client#33]
Please add a storeCounter with an expiry option.

In a 2006 message Greg wrote:

the storeCounter() method does not set an expiration, however, the
storeCounter() method is basically just a wrapper for set(), so an
expiration could most definitely be set.

http://lists.danga.com/pipermail/memcached/2006-March/002076.html

I am currently doing it manually and it would be nice to make this part of the API.

**Comment by newroot** [comment]
implemented in 2.6.4
