### ISSUE TITLE
NumberFormat exception in AsciiClient

### ISSUE THREAD

**Issue by joongonn** [gwhalin/Memcached-Java-Client#34]
After upgrading to 2.6.2, we're intermittently getting the below exceptions (against 1.4.5 server).

---

ERROR 2011-11-28 23:00:01,141 [com.danga.MemCached.MemCachedClient 740206481@qtp-1696446139-18735] For input string: "command"
java.lang.NumberFormatException: For input string: "command"
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:48)
        at java.lang.Integer.parseInt(Integer.java:449)
        at java.lang.Integer.parseInt(Integer.java:499)
##         at com.schooner.MemCached.AscIIClient.get(AscIIClient.java:734)

Looked into the code and found that it should be due to a breakdown of the below typical 'get' conversation with the server. Eg. a HIT yields
# setting a key

set the_key 1 0 13
Just a number
# retrieving the key

get the_key
VALUE the_key 32 13
Just a number
END

For the exception scenario, it seems that the AsciiClient was trying to pass a response from the server that looked like "VALUE the_key _command_ xxx". Wondering where did the 'command' keyword came from.

Anyone facing the same issue?

**Comment by newroot** [comment]
That's really strange, so you are using memcached 1.4.5 on linux box? I will have a try in my environment.

Or upgrade to 2.6.3, and have a try.

**Comment by joongonn** [comment]
Yeap we're running 1.4.5 servers in Linux environment.

**Comment by joongonn** [comment]
Just figured out that it's a user problem via traffic sniffing. We have code creating long keys that's causing the server to respond with

"CLIENT_ERROR bad command line format"

The server allows only up to 250 chars for keys as per the doc.

Suggestion for the client code to dump server response to log on exceptions, should help greatly with troubleshooting similar issues.
