### ISSUE TITLE
incorrect conditional statement for NOT_FOUND status

### ISSUE THREAD

**Issue by goldaxe** [gwhalin/Memcached-Java-Client#37]
Memcached-Java-Client 2.6.3

In code com.schooner.MemCached.AscIIClient

line 580： String line = new SockInputStream(sock, Integer.MAX_VALUE).getLine().split("\r\n")[0];
line 585： } else if (NOTFOUND.equals(line)) {

And com.danga.MemCached.MemCachedClient.NOTFOUND = "NOT_FOUND\r\n", but variable line = "NOT_FOUND", so the result of line 585 is always FALSE.

I use "NOTFOUND.startsWith(line)" to instead of "NOTFOUND.equals(line)" temporarily.

**Comment by newroot** [comment]
Thanks for figuring out this bug.

will be fixed in next version.
