### ISSUE TITLE
gets Boolean valued data throws NumberFormatException

### ISSUE THREAD

**Issue by giridharkannan** [gwhalin/Memcached-Java-Client#38]
In gets method of AscIIClient.java 
case 1:
break;
case 2:
    flag = Byte.parseByte(sb.toString());
break;

sb is parsed as bytes instead of Integer so throwing NumberFormatException

**Comment by newroot** [comment]
flag is a byte acctually.

**Comment by giridharkannan** [comment]
so is there a way to retrieve boolean data via gets

**Comment by newroot** [comment]
this client will serialize and deserialize the objects automatically, simply put the boolean data as Boolean, and get with a force (Boolean) conversion.

**Comment by giridharkannan** [comment]
Sorry for confusing you by telling boolean, Instead I meant Boolean.
Am not sure whether you have tried it in your environment. If you have come across ASCIIClient code flow the set method will use NativeHandler.getMarkerFlag(Object value) to get the flag of an object in order to avoid serialization and de-serialization of known Data Types. So in case of Boolean (flag value 8192) and many other data types whose value is above byte range respective gets will result in NumberFormatException.

This will not happen in case of get as flag is of type int.

**Comment by newroot** [comment]
Thanks for immediate information, I create a patch with 2.6.6

**Comment by giridharkannan** [comment]
Thanks for the quick fix
