### ISSUE TITLE
SockIOPool.SockIO.clearEOL()  has some wrong

### ISSUE THREAD

**Issue by markfly** [gwhalin/Memcached-Java-Client#39]
This "continue" need to be deleted?

// only stop when we see
                // \r (13) followed by \n (10)
                if (b[0] == 13) {
                    eol = true;
                    continue;
                }

```
            if (eol) {
                if (b[0] == 10)
                    break;

                eol = false;
            }
```

**Comment by markfly** [comment]
ps: the performance branch. gwhalin-Memcached-Java-Client-release_2.6.1-8

**Comment by newroot** [comment]
first of all, SockIOPool.SockIO.clearEOL()  is mock code, we don't use it in schooner's implementation, we just keep it there for compatible reasons.

the code snippets shows in your thread is to skip \r\n, so continue should be kept.
