### ISSUE TITLE
Can't Find JavaDocs

### ISSUE THREAD

**Issue by aviflax** [gwhalin/Memcached-Java-Client#4]
Can't find them here, don't see them in the download package. I can't find the site which used to host this library either.

**Comment by newroot** [comment]
Hi, aviflax,

Which version are you using?  2.0.1 or 2.5.0?
If you are using 2.0.1, you can find simple tutorial from the readme.
If you are using 2.5.0, you can find javadoc in the zip package. 
http://github.com/downloads/gwhalin/Memcached-Java-Client/java_memcached-release_2.5.0.zip

**Comment by aviflax** [comment]
I downloaded 2.0.1. Yes, I saw the tutorial. But it'd be nice if Javadocs were available somewhere.

**Comment by newroot** [comment]
Thanks for your comments, we will upload a 2.0.1 binary in the download area.
