### ISSUE TITLE
Problem with gets and cas

### ISSUE THREAD

**Issue by giridharkannan** [gwhalin/Memcached-Java-Client#40]
This thread is a continuation of issue #6

Mengli as you said, gets will return null in case of non existing value.

I guess the reason for introducing gets and cas is to avoid concurrency problems during add/update, Now if suppose 2 machines wants to add an entry simultaneously without race condition it is not possible as gets will return null (initial value will be null as the key wont exist. So we are forced to use put).

So present gets and sets address concurrent update problem and not Add.

One solution I could think of is to store the key and generate a cas value, if the key is not present, in memcache server itself

**Comment by mengli** [comment]
Hi giridharkannan,

First of all, we don't provide 'sets' method in this client.
Besides, I think the concurrent issue should be resolved by developers themselves and client should be kept simple.
Any way, I appreciate your deep understanding of concurrent programming.

Thank you!

Meng
