### ISSUE TITLE
PortRange feature Request

### ISSUE THREAD

**Issue by ravikumarg** [gwhalin/Memcached-Java-Client#44]
There are some parts of our code which specify a port and connect. This clashes with open mem-cached ports sometimes. We handle it the following way currently

SockIOPool.java
protected static Socket getSocket(String host, int port, int timeout) throws IOException {

```
        SocketChannel sock = SocketChannel.open();
        sock.socket().setReuseAddress(true);
        sock.socket().bind(new InetSocketAddress(getNextPortFromRange()));
        sock.socket().connect(new InetSocketAddress(host, port), timeout);
        return sock.socket();
```

}

TCPSockIO.java
public final static Socket getSocket(String host, int port, int timeout) throws IOException {
        SocketChannel sock = SocketChannel.open();
            sock.socket().setReuseAddress(true);
            sock.socket().bind(new InetSocketAddress(getNextPortFromRange()));
        sock.socket().connect(new InetSocketAddress(host, port), timeout);
        return sock.socket();
}

It would be great if we can expose an optional port range specifier as a config option to use.

**Comment by mengli** [comment]
Hi ravikumarg,

I think it is a application related feature which should be implemented by developers.

Thanks!

Meng
