### ISSUE TITLE
Memcached 的更新

### ISSUE THREAD

**Issue by fainfy** [gwhalin/Memcached-Java-Client#47]
<dependency>
            <groupId>com.whalin</groupId>
            <artifactId>Memcached-Java-Client</artifactId>
            <version>3.0.0</version>
        </dependency>

我通过Maven依赖Memcached，发现与提供的java_memcached-release_2.6.6版本中的包名不一致，但是里面的接口好像一致。
com.whalin.MemCached
com.danga.MemCached
这给我带来了许多困扰，让我不知道该如何选择，总之我认为这不是一个好的现象。

**Comment by newroot** [comment]
因为danga.com域名已经不受whalin控制了，所以从3.0.0起，为了满足maven的需求，我们修改了域名，改成whalin.com
其他保持不变，谢谢关注！

---

Xingen Wang

**Comment by jcookies** [comment]
I have a question, when I use PHP to add data to the Memcache, Java cannot read error! Data format into string! After viewing a MemCachedClient source code, found to be set flags, Java is based on the stored value types for flags, for example: public static final int MARKER_STRING = 32; and PHP is 0, so the question in this place, throw an exception
 example:
 94 [main] ERROR com.danga.MemCached.MemCachedClient - ++++ exception thrown while trying to get object from cache for key: operateLog
 94 [main] ERROR com.danga.MemCached.MemCachedClient - invalid stream header: 71717171
 java.io.StreamCorruptedException: invalid stream header: 71717171
 at java.io.ObjectInputStream.readStreamHeader(Unknown Source)
 at java.io.ObjectInputStream.(Unknown Source)
 at com.schooner.MemCached.ObjectTransCoder.decode(Unknown Source)
 at com.schooner.MemCached.AscIIClient.get(Unknown Source)
 at com.schooner.MemCached.AscIIClient.get(Unknown Source)
 at com.schooner.MemCached.AscIIClient.get(Unknown Source)
 at com.danga.MemCached.MemCachedClient.get(Unknown Source)
