### ISSUE TITLE
storeCounter

### ISSUE THREAD

**Issue by jrodbeta** [gwhalin/Memcached-Java-Client#50]
For performance branch:

In master the storeCounter overloads set() with primitiveAsString as true.  The performance branch currently doesn't do this so storeCounter will cause the server to throw the following error message unless the flag is set for the entire instance of the client:

CLIENT_ERROR cannot increment or decrement non-numeric value

**Comment by mengli** [comment]
Hi jrodbeta,

Thank you for your report. This issue has been fixed in my recent submission. Please download the latest source code and have a try.

Many thanks!

Meng
