### ISSUE TITLE
incompatibility with a python client

### ISSUE THREAD

**Issue by yamt** [gwhalin/Memcached-Java-Client#51]
2.6.6 stores a String value with flag=32 even with setPrimitiveAsString(true).
a python client (installed with pip install python-memcached) can not get the value.

MemCached: unknown flags on get: 20
 13: handler exception: local variable 'val' referenced before assignment

i guess it's better to use flag=0 for setPrimitiveAsString(true) clients as it seems that
older versions used to do.

**Comment by newroot** [comment]
```
public static final int MARKER_BYTE = 1;
public static final int MARKER_BOOLEAN = 8192;
public static final int MARKER_INTEGER = 4;
public static final int MARKER_LONG = 16384;
public static final int MARKER_CHARACTER = 16;
public static final int MARKER_STRING = 32;
public static final int MARKER_STRINGBUFFER = 64;
public static final int MARKER_FLOAT = 128;
public static final int MARKER_SHORT = 256;
public static final int MARKER_DOUBLE = 512;
public static final int MARKER_DATE = 1024;
public static final int MARKER_STRINGBUILDER = 2048;
public static final int MARKER_BYTEARR = 4096;
public static final int MARKER_OTHERS = 0x00;
```

**Comment by mengli** [comment]
Hi yamt,

We refined encoding flags in performance. Please find them in newroot's comment.

Meng
