### ISSUE TITLE
File descriptor leak in SchoonerSockIOPool

### ISSUE THREAD

**Issue by jerpowers** [gwhalin/Memcached-Java-Client#52]
When creating a MemCachedClient against a bad/nonexistent memcached server, every call to the client will result in a file descriptor being claimed for a socket, but then never closed.  These open FDs will stick around for the length of the process, even if the memcached server becomes valid.

Using 3.0.1, with tcp connection.

Looks to be caused by the following:

https://github.com/gwhalin/Memcached-Java-Client/blob/performance/src/main/java/com/schooner/MemCached/SchoonerSockIOPool.java#L1476

When requesting a connection from the pool, it will attempt to create a new TCPSockIO object (via GenericObjectPool.borrowObject()).  Instantiation of TCPSockIO attempts to create and connect to a socket for the memcached server.  But it does this as a two-step process: first opening the socket, then attempting to connect to it.  If the connection throws an exception the socket is never closed.  And since the TCPSockIO object was never fully instantiated, the object pool simply registers the exception and continues - with the next request repeating the process.

Fix should be relatively simple.  Either use the SocketChannel convenience open method (which does not accept a timeout):

http://docs.oracle.com/javase/6/docs/api/java/nio/channels/SocketChannel.html#open%28java.net.SocketAddress%29

Or wrap the socket connect() call in a try/catch, and close if needed:

<pre>
diff --git a/src/main/java/com/schooner/MemCached/SchoonerSockIOPool.java b/src/main/java/com/schooner/MemCached/SchoonerSockIOPool.java
index 396894a..7f4abe0 100644
--- a/src/main/java/com/schooner/MemCached/SchoonerSockIOPool.java
+++ b/src/main/java/com/schooner/MemCached/SchoonerSockIOPool.java
@@ -1474,7 +1474,14 @@ public class SchoonerSockIOPool {
                 */
                protected final static Socket getSocket(String host, int port, int timeout) throws IOException {
                     SocketChannel sock = SocketChannel.open();
+                    try {
                        sock.socket().connect(new InetSocketAddress(host, port), timeout);
+                     } catch (IOException e) {
+                        sock.socket().close();
+                        throw e;
+                    }
                     return sock.socket();
                }
 
</pre>

**Comment by newroot** [comment]
Great job. Really thanks for fix, I wll apply.

**Comment by mengli** [comment]
Let's close this issue.
