### ISSUE TITLE
the build.xml line 71 "<include name="com/danga/MemCached/**/*" />" is not corrent

### ISSUE THREAD

**Issue by sunwill** [gwhalin/Memcached-Java-Client#61]
the build.xml line 71 "<include name="com/danga/MemCached/**/*" />" is not corrent
should be “<include name="com/whalin/MemCached/**/*" />”

**Comment by newroot** [comment]
Thanks for the information.

**Comment by mengli** [comment]
Hi sunwill,

Thank you for your information!

Meng
