### ISSUE TITLE
Client Hanging When Serializing Large (1.5mb) Objects

### ISSUE THREAD

**Issue by ghost** [gwhalin/Memcached-Java-Client#64]
As of MemCached version 1.4.2 it is possible to specify a maximum value size larger than 1mb when starting the server. 

It seems that this client isn't handling larger length objects correctly. I have input that has a list of XML data. If the data is small, everything works okay. If the data is larger (~1.5mb) it fails to enter and actually seems to hang (though it doesn't, I'll explain what's happening below).

We have a couple other client libraries and can put the same long data set in using those other libraries, so the problem seems to be specific to this client library. Also, it happens whether the data is wrapped inside a more complex java object or if its all in a simple string object. I don't suspect the object serializer.

If I put our server in -vvv (very verbose) mode, when I try to set the long data set in the cache I see the following:
![memcached_client_issue](https://f.cloud.github.com/assets/4729831/669799/9fb8ed96-d834-11e2-9832-89cf26f7af6f.jpg)

It seems that the initial "set" command is malformed. It has 0 for the flag, 0 for the expiry time, then gives an error. Then comes a strange character which I assume is a mangled version of what SHOULD be the length, and then the data starts coming in.

Because the server gave an error for the set command, it doesn't know the data is actually supposed to be stored and it gives an error for each and every line as if its an unknown command being received. Since there are tens of thousands of lines and each line is getting an error from the server, it takes a while for our application to finish executing, giving the illusion that its hanging for some of our more impatient developers (a successful set is milliseconds, so waiting 5-10 minutes is not intuitive).

For the record we are using client version 2.6.3 and server version 1.4.4.

**Comment by mengli** [comment]
Hi Geradenn,

Thank you for your information.
My question is what kind of protocol do you use? TCP or UDP?

Meng

**Comment by newroot** [comment]
By default the buffer size of memcached client is 1MB.
You can setBufferSize with a big size in SockIOPool to handle those >1MB cases.
BTW, don't forget to increase slab size in server side.

**Comment by mengli** [comment]
Hi Geradenn,

You can use -I option to override the size of each slab page and adjust the max item size.

Meng
