### ISSUE TITLE
Possible native resource leak when number of connections exceeds pool size

### ISSUE THREAD

**Issue by ghost** [gwhalin/Memcached-Java-Client#7]
This is happening in the performance branch.

If I read the code correctly, a one time socket will be created if the pool is full and all the sockets in it are being used.  Then in AsciiClient class, sock.close() is called in the finally clause of all the command methods.  Since sock.close() will not actually close the socket and will only put pooled sockets back in the pool, these one time sockets are never closed.  This is reproducible by making the number of concurrent clients much more than the pool size.  I was getting "Too many open files" within two minutes.  The problem disappeared after I applied a fix.

**Comment by mengli** [comment]
Hi noisebar,

Thanks very much for trying our new version of memcached client.

According to your description, we reproduced the bug and a bug fix has already been applied to the source code repository.

Could you please check it out and have a try?

But I don't think it is a good practice to set the max connection pool size much smaller than the thread number. It will cause frequent connection creation and destory, which will decrease the performance of our client. 

Thanks again for giving us the useful information.

**Comment by ghost** [comment]
Thanks for the quick fix.  I agree that my test scenario is not a good production set up.  But I'd like to make sure that it can handle that.  I'm working on determining the optimal pool size.

~Simon
