### ISSUE TITLE
Memcached信息过期的问题

### ISSUE THREAD

**Issue by WillawokE** [gwhalin/Memcached-Java-Client#74]
java_memcached-release_2.6.6.jar，用的是这个client，使用了set(key, value, timeout)设置过期，为什么到了过期时间，使用get出来的还是有value而不是null。

**Comment by zhanghanlin** [comment]
检查下SET的时候设置的时间，看下SET的时间单位是什么！

## 

try {
    String name = "AndyLau.ZHL";
} catch (NullPointerException e) {
    // TODO: handle exception
    e.printStackTrace();
}

在 2014-07-18 05:33:33，Will" notifications@github.com 写道：

java_memcached-release_2.6.6.jar，用的是这个client，使用了set(key, value, timeout)设置过期，为什么到了过期时间，使用get出来的还是有value而不是null。
